---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "grabber.fullname" . }}
  labels:
    app: crawler
    component: grabber
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: grabber
      release: {{ .Release.Name }}
  template:
    metadata:
      name: grabber
      labels:
        app: crawler
        component: grabber
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: grabber
        imagePullPolicy: Always 
        env:
        - name: MONGO
          value: {{ .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{ .Values.mongoPort | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{ .Values.rabbitHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{ .Values.rabbitQueue | default "rabbitmq" | quote }}
        - name: RMQ_USERNAME
          value: {{ .Values.rabbitUsername | default "crawler" | quote }}
        - name: RMQ_PASSWORD
          value: {{ .Values.rabbitPassword | default "crawler" | quote }}
        - name: CHECK_INTERVAL
          value: {{ .Values.checkInterval | default "1" | quote }}
        - name: URL
          value: {{ .Values.url | default "https://vitkhab.github.io/search_engine_test_site/" | quote }}


