---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "crawler-ui.fullname" . }}
  labels:
    app: crawler
    component: crawler-ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui-pod
      labels:
        app: crawler
        component: crawler-ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler-ui
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler-ui
          protocol: TCP
        env:
        - name: MONGO
          value: {{  .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.mongoPort | default "27017" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
