{
 "title": "Crawler dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "web_pages_served",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "web_pages_served{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "web_page_gen_time_count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "web_page_gen_time_count{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "crawler_pages_parsed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "crawler_pages_parsed{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "crawler_page_parse_time_bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_page_parse_time_bucket{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Pages parsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_pages_parsed{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "web_page_gen_time_bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_page_gen_time_bucket{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "web_page_gen_time_sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_page_gen_time_sum{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}